
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* pace_clk_html = R"=====(
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Interval Timer Setup</title>
    <style>
      body {
        font-family: sans-serif;
        background: #f2f2f2;
        margin: 0;
        padding: 1em;
      }

      .container {
        max-width: 400px;
        margin: auto;
        background: white;
        padding: 1em;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
      }

      h2 {
        text-align: center;
        margin-bottom: 1em;
      }

      .interval-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 10px;
      }

      .interval-row label {
        flex: 1;
      }

      .interval-row input {
        width: 80px;
        padding: 8px;
        font-size: 1em;
      }

      button {
        width: 100%;
        padding: 12px;
        margin-top: 10px;
        font-size: 1em;
        background-color: #0078D7;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
      }

      button:hover {
        background-color: #005fa3;
      }

      .controls {
        display: flex;
        gap: 10px;
        margin-top: 20px;
      }

      .controls button {
        flex: 1;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>Interval Sequence Setup</h2>

      <div id="intervals">
        <div class="interval-row">
          <input type="text" value="Interval 1" class="label-input" />
          <input type="number" value="60" min="1" class="time-input" />
          <button onclick="removeInterval(this)">Remove</button>
        </div>
        <div class="interval-row">
          <input type="text" value="Interval 2" class="label-input" />
          <input type="number" value="55" min="1" class="time-input" />
          <button onclick="removeInterval(this)">Remove</button>
        </div>
        <div class="interval-row">
          <input type="text" value="Interval 3" class="label-input" />
          <input type="number" value="50" min="1" class="time-input" />
          <button onclick="removeInterval(this)">Remove</button>
        </div>
      </div>

      <button onclick="addInterval()">+ Add Interval</button>

      <div class="controls">
        <button onclick="startSequence()">Start</button>
        <button onclick="resetSequence()">Reset</button>
      </div>
    </div>

    <script src="utils.js"></script>
    <script src="pace_clk.js"></script>

  </body>
</html>
)=====";
