
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* utils_js = R"=====(
// JavaScript for Water Polo Scoreboard Utilities Functions

function formatTime(seconds) {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return String(minutes).padStart(2, '0') + ":" + String(remainingSeconds).padStart(2, '0');
}

function isNumber(str) {
    return !isNaN(str) && str.trim() !== ""; // Ensure it's not empty or whitespace
}
)=====";
