# embed_scripts.py
import os

######################################################################
# Home Page Scripts
# Define the file paths
script_file = os.path.join("src", "homepage.js")
header_file = os.path.join("include", "homepage_js.h")

# Read the JavaScript file
with open(script_file, "r") as f:
    js_content = f.read()

# Generate the C++ header file
header_content = f"""
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* homepage_js = R"=====(
{js_content}
)=====";
"""

# Write the header file
with open(header_file, "w") as f:
    f.write(header_content)


######################################################################
# Game & Shot Clk Page Scripts
# Define the file paths
script_file = os.path.join("src", "game_and_shot_clk.js")
header_file = os.path.join("include", "game_and_shot_clk_js.h")

# Read the JavaScript file
with open(script_file, "r") as f:
    js_content = f.read()

# Generate the C++ header file
header_content = f"""
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* game_and_shot_clk_js = R"=====(
{js_content}
)=====";
"""

# Write the header file
with open(header_file, "w") as f:
    f.write(header_content)

######################################################################
# Shot Clk Page Scripts
# Define the file paths
script_file = os.path.join("src", "shot_clk.js")
header_file = os.path.join("include", "shot_clk_js.h")

# Read the JavaScript file
with open(script_file, "r") as f:
    js_content = f.read()

# Generate the C++ header file
header_content = f"""
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* shot_clk_js = R"=====(
{js_content}
)=====";
"""

# Write the header file
with open(header_file, "w") as f:
    f.write(header_content)

######################################################################
# Game Clk Page Scripts
# Define the file paths
script_file = os.path.join("src", "game_clk.js")
header_file = os.path.join("include", "game_clk_js.h")

# Read the JavaScript file
with open(script_file, "r") as f:
    js_content = f.read()

# Generate the C++ header file
header_content = f"""
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* game_clk_js = R"=====(
{js_content}
)=====";
"""

# Write the header file
with open(header_file, "w") as f:
    f.write(header_content)

######################################################################
# Utility Scripts
# Define the file paths
script_file = os.path.join("src", "utils.js")
header_file = os.path.join("include", "utils_js.h")

# Read the JavaScript file
with open(script_file, "r") as f:
    js_content = f.read()

# Generate the C++ header file
header_content = f"""
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* utils_js = R"=====(
{js_content}
)=====";
"""

# Write the header file
with open(header_file, "w") as f:
    f.write(header_content)

######################################################################
# Game Clk Only Page Scripts
# Define the file paths
script_file = os.path.join("src", "game_clk_only.js")
header_file = os.path.join("include", "game_clk_only_js.h")

# Read the JavaScript file
with open(script_file, "r") as f:
    js_content = f.read()

# Generate the C++ header file
header_content = f"""
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* game_clk_only_js = R"=====(
{js_content}
)=====";
"""

# Write the header file
with open(header_file, "w") as f:
    f.write(header_content)

######################################################################
# Game Clk Page Scripts
# Define the file paths
script_file = os.path.join("src", "shot_clk_only.js")
header_file = os.path.join("include", "shot_clk_only_js.h")

# Read the JavaScript file
with open(script_file, "r") as f:
    js_content = f.read()

# Generate the C++ header file
header_content = f"""
// This file is auto-generated by the embed_scripts.py script.
// Do not edit this file directly.
#pragma once
const char* shot_clk_only_js = R"=====(
{js_content}
)=====";
"""

# Write the header file
with open(header_file, "w") as f:
    f.write(header_content)